import { Dataset } from "./types/datasets.interface";

export const mockDatasets = [
  {
    id: 1,
    name: "Tech requirements.pdf",
    type: "PDF",
    status: "uploaded",
    createdAt: "Jan 4, 2024",
    creator: "Olivia Rhye",
    email: "olivia@untitledui.com",
  },
  {
    id: 2,
    name: "Dashboard screenshot.jpg",
    type: "JPG",
    status: "connected",
    createdAt: "Jan 4, 2024",
    creator: "Phoenix Baker",
    email: "phoenix@untitledui.com",
  },
  {
    id: 3,
    name: "Dashboard prototype recording.mp4",
    type: "MP4",
    status: "connected",
    createdAt: "Jan 2, 2024",
    creator: "Lana Steiner",
    email: "lana@untitledui.com",
  },
  {
    id: 4,
    name: "Dashboard prototype FINAL.fig",
    type: "FIG",
    status: "connected",
    createdAt: "Jan 6, 2024",
    creator: "Demi Wilkinson",
    email: "demi@untitledui.com",
  },
  {
    id: 5,
    name: "UX Design Guidelines.docx",
    type: "DOCX",
    status: "connected",
    createdAt: "Jan 8, 2024",
    creator: "Candice Wu",
    email: "candice@untitledui.com",
  },
  {
    id: 6,
    name: "Dashboard interaction.aep",
    type: "AEP",
    status: "error",
    createdAt: "Jan 6, 2024",
    creator: "Natali Craig",
    email: "natali@untitledui.com",
  },
  {
    id: 7,
    name: "Dashboard interaction.aep",
    type: "AEP",
    status: "connected",
    createdAt: "Jan 6, 2024",
    creator: "Natali Craig",
    email: "natali@untitledui.com",
  },
  {
    id: 8,
    name: "Dashboard screenshot.jpg",
    type: "JPG",
    status: "connected",
    createdAt: "Jan 4, 2024",
    creator: "Phoenix Baker",
    email: "phoenix@untitledui.com",
  },
  {
    id: 9,
    name: "Dashboard prototype recording.mp4",
    type: "MP4",
    status: "connected",
    createdAt: "Jan 2, 2024",
    creator: "Lana Steiner",
    email: "lana@untitledui.com",
  },
  {
    id: 10,
    name: "Dashboard prototype FINAL.fig",
    type: "FIG",
    status: "connected",
    createdAt: "Jan 6, 2024",
    creator: "Demi Wilkinson",
    email: "demi@untitledui.com",
  },
  {
    id: 11,
    name: "UX Design Guidelines.docx",
    type: "DOCX",
    status: "connected",
    createdAt: "Jan 8, 2024",
    creator: "Candice Wu",
    email: "candice@untitledui.com",
  },
  {
    id: 12,
    name: "Dashboard interaction.aep",
    type: "AEP",
    status: "error",
    createdAt: "Jan 6, 2024",
    creator: "Natali Craig",
    email: "natali@untitledui.com",
  },
  {
    id: 13,
    name: "Dashboard interaction.aep",
    type: "AEP",
    status: "connected",
    createdAt: "Jan 6, 2024",
    creator: "Natali Craig",
    email: "natali@untitledui.com",
  },
] as Dataset[];
